remote_theme: peterdesmet/petridish@1.1

# SITE SETTINGS
title: Synthetic Data for Machine Learning Seminar       # Title in top navigation bar (navbar) and <head>
description: Website of the Synthetic Data for Learning Seminar at IMPA 2021
author: Hallison Paz & Luiz Velho                   # Used for copyright statement in footer
# url: "https://peterdesmet.github.io"  # No slash at the end
baseurl: "/syntheticlearning"                 # Only required if your site is on a subdomain e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                        # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/about/#links

# SOCIAL PROFILES
email: hallpaz@impa.br           # Social icon in footer
twitter_username: visgraflab           # Social icon in footer
github_username: visgraf            # Social icon in footer

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3                        # Show x number of latest posts on homepage, can be 0
tweets_on_home: true                    # Show Twitter feed of twitter_username on homepage
archive_permalink: /blog/               # Permalink of page using archive.html layout, required when using post categories
logo: /assets/visgraflogo.jpg  # Logo in navbar, will be displayed with 30px height
colors:
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#007bff"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well with white
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons
